theme: advanced
valid_elements: "a[href|target=_blank],strong,br,img[src|width|height|align|hspace|vspace],i,em,ul,ol,li,p,u,blockquote"
plugins:
- paste
- contextmenu
- inlinepopups
dialog_type: "modal"
theme_advanced_buttons1: "bold,italic,|,bullist,numlist,blockquote,|,link,unlink,image,code"
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
theme_advanced_statusbar_location: "none"
theme_advanced_resizing: true
theme_advanced_path: false